# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
    # Run Ruff’s linter + fixes, but do *not* exit non-zero on fix
    - id: ruff
      args: [--fix, --format]
