# .github/workflows/ci.yml
name: CI

# Grant write access for Pages deploy
permissions:
  contents: write      # allow pushing commits
  pages: write         # allow updating GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # Removed 3.13 as it might not be fully supported by all dependencies yet

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall --no-cache-dir .[dev]

      - name: Run tests with coverage
        run: pytest --cov=pyforestry --cov-report=xml --cov-report=html --cov-fail-under=50

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: htmlcov/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage.xml
          fail_ci_if_error: true

  build-and-deploy-docs:
    runs-on: ubuntu-latest
    needs: test-and-coverage
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 # Or your desired version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies and documentation-specific dependencies
          pip install .[dev]
          pip install -r docs/requirements.txt

      # NEW STEP: Generate API documentation .rst files
      - name: Generate API docs
        run: |
          sphinx-apidoc -f -o docs/source/api src/pyforestry

      # MODIFIED STEP: Build the Sphinx docs from the root
      - name: Build Sphinx docs
        run: make -f docs/Makefile html

      # This step should now work correctly
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
